### ISSUE TITLE
Setting "enable-particles: false" causes the server to crash

### ISSUE THREAD

**Issue by HunkyMunky** [EnvyWare/PixelHuntRemastered#6]
**Crash report:**
```
[01:43:27 ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@297a2782:
 java.lang.NullPointerException: null
        at com.envyful.pixel.hunt.remastered.forge.shade.envy.api.forge.items.ItemBuilder.<init>(ItemBuilder.java:49) ~[ItemBuilder.class:?]
        at com.envyful.pixel.hunt.remastered.forge.hunt.ForgePixelHunt.display(ForgePixelHunt.java:69) ~[ForgePixelHunt.class:?]
        at com.envyful.pixel.hunt.remastered.forge.ui.HuntUI.open(HuntUI.java:50) ~[HuntUI.class:?]
        at com.envyful.pixel.hunt.remastered.forge.commands.PixelHuntCommand.lambda$executeCommand$0(PixelHuntCommand.java:28) ~[PixelHuntCommand.class:?]
        at com.envyful.pixel.hunt.remastered.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener.onServerTick(ServerTickListener.java:29) ~[ServerTickListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_149_ServerTickListener_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:96) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:275) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[01:43:27 ERROR]: Index: 9 Listeners:
[01:43:27 ERROR]: 0: NORMAL
[01:43:27 ERROR]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@5df045e3 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 2: ASM: de.waterdu.aquaapi.ui.internal.AquaUIListener@3914141c onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 3: ASM: de.waterdu.aquagts.atlantis.ui.internal.AquaUIListener@4a52f6cc onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 4: ASM: de.waterdu.aquagyms.event.Events@538d31cb onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 5: ASM: de.waterdu.aquagyms.gym.queue.Queue@54754e43 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 6: ASM: com.envyful.pixel.hunt.remastered.forge.task.ParticleDisplayTask@50eec6b3 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 7: ASM: com.pixelmonmod.pixelmon.TickHandler@1a0c5360 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 8: ASM: com.pixelmonmod.pixelmon.spawning.TrackingSpawnerCoordinator@2137b14a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 9: ASM: com.envyful.pixel.hunt.remastered.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener@321b751f onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: 10: ASM: com.envyful.pixel.hunt.remastered.forge.shade.envy.api.forge.gui.ForgeGuiTracker$ForgeGuiTickListener@29864ca6 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[01:43:27 ERROR]: Encountered an unexpected exception
```

**Comment by HunkyMunky** [comment]
Running pixelhunt 3.0.0
```
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: com.envyful.pixel.hunt.remastered.forge.shade.configurate.serialize.SerializationException: [hunts, one, generator-config, blocked-types] of type java.util.Map<java.lang.String, com.envyful.pixel.hunt.remastered.forge.config.PixelHuntConfig$HuntConfig>: No applicable type serializer for type
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.serialize.AbstractListChildSerializer.serialize(AbstractListChildSerializer.java:77)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperImpl.saveSingle(ObjectMapperImpl.java:143)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperImpl.save(ObjectMapperImpl.java:114)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperFactoryImpl.serialize(ObjectMapperFactoryImpl.java:251)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperImpl.saveSingle(ObjectMapperImpl.java:143)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:105)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.serialize.MapSerializer.deserialize(MapSerializer.java:70)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.serialize.MapSerializer.deserialize(MapSerializer.java:35)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.reference.ValueReferenceImpl.deserializedValueFrom(ValueReferenceImpl.java:74)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.reference.ValueReferenceImpl.<init>(ValueReferenceImpl.java:63)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.reference.ValueReferenceImpl.<init>(ValueReferenceImpl.java:68)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.reference.ManualConfigurationReference.referenceTo(ManualConfigurationReference.java:135)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.reference.ConfigurationReference.referenceTo(ConfigurationReference.java:350)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.configurate.reference.ConfigurationReference.referenceTo(ConfigurationReference.java:310)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.shade.envy.api.config.yaml.YamlConfigFactory.getInstance(YamlConfigFactory.java:70)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.PixelHuntForge.loadConfig(PixelHuntForge.java:54)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at com.envyful.pixel.hunt.remastered.forge.PixelHuntForge.onPreInit(PixelHuntForge.java:42)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraftforge.eventbus.ASMEventHandler_10_PixelHuntForge_onPreInit_FMLServerAboutToStartEvent.invoke(.dynamic)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[03:35:09] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[03:35:10] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95)
[03:35:10] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:166)
[03:35:10] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861)
[03:35:10] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
[03:35:10] [Server thread/INFO] [STDERR/]: [com.envyful.pixel.hunt.remastered.forge.PixelHuntForge:loadConfig:56]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[03:35:10] [Server thread/ERROR] [forge/EventBus]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.envyful.pixel.hunt.remastered.forge.PixelHuntForge@2ba852d1 onPreInit(Lnet/minecraftforge/fml/event/server/FMLServerAboutToStartEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2872/0x0000000800b95c40@50507268
		3: ASM: com.pixelmonmod.pixelmon.Pixelmon@22abd825 onServerAboutToStart(Lnet/minecraftforge/fml/event/server/FMLServerAboutToStartEvent;)V
java.lang.NullPointerException
	at com.envyful.pixel.hunt.remastered.forge.hunt.PixelHuntForgeFactory.reloadHunts(PixelHuntForgeFactory.java:26)
	at com.envyful.pixel.hunt.remastered.forge.hunt.PixelHuntForgeFactory.<init>(PixelHuntForgeFactory.java:19)
	at com.envyful.pixel.hunt.remastered.forge.PixelHuntForge.onPreInit(PixelHuntForge.java:45)
	at net.minecraftforge.eventbus.ASMEventHandler_10_PixelHuntForge_onPreInit_FMLServerAboutToStartEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:166)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
	at java.base/java.lang.Thread.run(Thread.java:834)

[03:35:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at com.envyful.pixel.hunt.remastered.forge.hunt.PixelHuntForgeFactory.reloadHunts(PixelHuntForgeFactory.java:26) ~[pixelhuntremastered:?] {re:classloading}
	at com.envyful.pixel.hunt.remastered.forge.hunt.PixelHuntForgeFactory.<init>(PixelHuntForgeFactory.java:19) ~[pixelhuntremastered:?] {re:classloading}
	at com.envyful.pixel.hunt.remastered.forge.PixelHuntForge.onPreInit(PixelHuntForge.java:45) ~[pixelhuntremastered:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_10_PixelHuntForge_onPreInit_FMLServerAboutToStartEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:166) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
[03:35:10] [Server thread/FATAL] [forge/ForgeMod]: Preparing crash report with UUID 07acf194-f64e-4e57-a5b7-de3e728f6179
[03:35:10] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /Users/briantan/Desktop/Arclight 1.16/./crash-reports/crash-2022-06-21_03.35.10-server.txt
[03:35:10] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[03:35:10] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[03:35:10] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
```

**Comment by HunkyMunky** [comment]
Good news is that the server doesn't crash on start-up in 3.0.1, but the server is still crashing when /hunt is used.

I'm using the default config with only 1 setting changed which is `enable-particles: false`.
```
# © EnvyWare Ltd Software 2022
# For assistance visit https://discord.envyware.co.uk

config-interface:
    title: ''
    height: 6
    fill-type: BLOCK
    filler-items:
        one:
            enabled: true
            type: minecraft:stained_glass_pane
            amount: '1'
            damage: '14'
            name: ' '
            flags: []
            lore: []
            enchants: {}
            nbt: {}
spawn-broadcast: []
timeout-broadcast: []
extra-lore:
- ''
- '&bTime remaining: %time%'
pre-lore:
- ''
- This goes at the top
enable-particles: false
hunts:
    one:
        reward-commands:
        - broadcast Testing %player%
        reward-description:
        - Hello
        generator-config:
            blocked-types: []
            species-requirement: true
            allow-legends: false
            allow-ultra-beasts: false
            gender-requirement: true
            growth-requirement: false
            nature-requirement: false
            potential-growth-requirements: 2
            potential-nature-requirements: 2
            allow-evolutions: false
            iv-requirement: true
            random-i-v-generation: false
            min-i-v-percentage: 30
            max-i-v-percentage: 100
            only-legends: false
        random-commands: false
        max-ivs: false
        iv-multiplier-enabled: false
        iv-multiplier: 1.5
        max-duration-minutes: 30
        gui-x: 1
        gui-y: 1
```

**Comment by danorris709** [comment]
Can you please provide the crash report?

**Comment by HunkyMunky** [comment]
Crash report:
```
[00:20:25] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: HunkyMunky issued server command: /hunt
[00:20:25] [Server thread/ERROR] [forge/EventBus]: Exception caught during firing event: null
	Index: 5
	Listeners:
		0: NORMAL
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@39ce7984 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		2: ASM: com.pixelmonmod.pixelmon.TickHandler@5779d56a onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		3: ASM: com.envyful.pixel.hunt.remastered.forge.task.ParticleDisplayTask@7ea65338 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		4: ASM: com.pixelmonmod.pixelmon.spawning.TrackingSpawnerCoordinator@21894774 onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		5: ASM: com.envyful.pixel.hunt.remastered.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener@69773e79 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.lang.NullPointerException
	at com.envyful.pixel.hunt.remastered.forge.hunt.ForgePixelHunt.display(ForgePixelHunt.java:69)
	at com.envyful.pixel.hunt.remastered.forge.ui.HuntUI.open(HuntUI.java:31)
	at com.envyful.pixel.hunt.remastered.forge.commands.PixelHuntCommand.lambda$executeCommand$0(PixelHuntCommand.java:28)
	at com.envyful.pixel.hunt.remastered.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener.onServerTick(ServerTickListener.java:29)
	at net.minecraftforge.eventbus.ASMEventHandler_126_ServerTickListener_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:785)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
	at java.base/java.lang.Thread.run(Thread.java:834)

[00:20:25] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at com.envyful.pixel.hunt.remastered.forge.hunt.ForgePixelHunt.display(ForgePixelHunt.java:69) ~[pixelhuntremastered:?] {re:classloading}
	at com.envyful.pixel.hunt.remastered.forge.ui.HuntUI.open(HuntUI.java:31) ~[pixelhuntremastered:?] {re:classloading}
	at com.envyful.pixel.hunt.remastered.forge.commands.PixelHuntCommand.lambda$executeCommand$0(PixelHuntCommand.java:28) ~[pixelhuntremastered:?] {re:classloading}
	at com.envyful.pixel.hunt.remastered.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener.onServerTick(ServerTickListener.java:29) ~[pixelhuntremastered:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_126_ServerTickListener_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:785) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
[00:20:25] [Server thread/FATAL] [forge/ForgeMod]: Preparing crash report with UUID 385f650e-b694-4f75-8e2f-70b0e52c8495
[00:20:25] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /Users/briantan/Desktop/Arclight 1.16/./crash-reports/crash-2022-06-22_00.20.25-server.txt
[00:20:25] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[00:20:25] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[00:20:25] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: HunkyMunky lost connection: Server closed
```
